name: Test & Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cli-test:
    name: CLI Test & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenCL Headers & Drivers
        run: |
          sudo apt-get update
          sudo apt-get install -y ocl-icd-opencl-dev pocl-opencl-icd

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Run CPU Tests
        working-directory: ./cli
        run: cargo test --verbose
        
      - name: Run GPU Tests
        working-directory: ./cli
        run: cargo test --verbose --features gpu


      - name: Build with GPU
        working-directory: ./cli
        run: cargo build --verbose --release --features gpu
