name: Test & Build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  cli-test:
    name: CLI Test & Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install OpenCL Headers
      run: |
        sudo apt-get update
        sudo apt-get install -y ocl-icd-opencl-dev

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Run Tests
      working-directory: ./cli
      run: cargo test --verbose --features gpu

    - name: Build
      working-directory: ./cli
      run: cargo build --verbose --release --features gpu